UI/UI auth login
money-fragments/money-fragments-client pull request #26
Opened 2023-01-21 14:54 UTC by dollorofkorea

## What is this PR? :mag:
Auth Login UI는 앞으로 보입니다.
-

## branch

- ui/ui-Auth-login -> develop

## Changes :memo:
로그인 화면만 ui제작되었습니다.
Global style에 anchor를 추가하여 링크 시 링크 색깔이 되는 것을 수정하였습니다.
white와 black은 승인 전으로 적용은 하지 않았습니다. 
일단 ui적용 시 #컬러로 적용했으며 승인될 경우 추후 기능 구현 시 white 또는 black으로 수정하겠습니다. 

-
#8 
by @dollorofkorea

2023-01-21 15:16 UTC, frankkim92 submitted a review, later dismissed
고생하셨습니다.😀

2023-01-22 04:00 UTC, Jeremy-Kr requested changes
text 태그... 말고 다른 태그를 상속해서 사용해봅시다!

2023-01-22 04:00 UTC, Jeremy-Kr commented on src/components/auth/Login.tsx
> +`;
text라는 태그는 없는걸로 알고있습니다! H6을 상속해서 사용해 보시는건 어떨까요?

2023-01-22 04:00 UTC, Jeremy-Kr commented on src/components/auth/Login.tsx
> +`;
아래에 나머지 text 태그들도 마찬가지 의견입니다.

2023-01-22 04:44 UTC, dollorofkorea commented
네 그럼 오늘 수정해서 다시 커밋하겠습니다

2023-01-22 04:55 UTC, dollorofkorea commented on src/components/auth/Login.tsx
> +`;
네.오늘 수정해서 다시 커밋하겠습니다.

2023-01-22 07:14 UTC, dollorofkorea commented
## What is this PR? :mag:
Auth Login UI는 앞으로 보입니다. 
-

## branch

- ui/ui-Auth-login -> develop

## Changes :memo:
textComponents 사용으로 통일 (기존 text태그 삭제)
최신  dev merge
색상 white와 black 으로 변경
-
#8 
by @dollorofkorea

2023-01-22 08:49 UTC, Jeremy-Kr approved these changes
LGTM

2023-01-22 10:31 UTC, harenohee approved these changes
확인했습니다. 🥹

2023-01-22 10:32 UTC, harenohee approved these changes
H6 태그 적용 확인했습니당

2023-01-22 10:51 UTC, merged