Feat/button component
money-fragments/money-fragments-client pull request #28
Opened 2023-01-22 11:22 UTC by frankkim92

## What is this PR? :mag:
CustomButton을 사용할 수 있습니다.
-

## branch

- feature/button-component -> develop

## Changes :memo:

- 커스텀 버튼이 컴포넌트가 추가되었습니다.
- 호버 기능이 추가되었습니다. 

by @frankkim92 #1

2023-01-22 11:46 UTC, Jeremy-Kr approved these changes
LGTM

2023-01-22 11:46 UTC, Jeremy-Kr commented on src/components/common/ButtonComponents.tsx
> +      ? (props: any) => props.theme.colors[`${props.backgroundColor}`]
요부분 제가 한번 고쳐볼게요

2023-01-22 11:46 UTC, Jeremy-Kr commented on src/components/common/ButtonComponents.tsx
> +      ? (props: any) => props.theme.colors[`${props.backgroundColor}`]
못했읍니다..

2023-01-22 11:48 UTC, frankkim92 commented on src/components/common/ButtonComponents.tsx
> +      ? (props: any) => props.theme.colors[`${props.backgroundColor}`]
앗.. 감사합니다.

2023-01-22 11:51 UTC, harenohee submitted a review, later dismissed
귯 확인했습니당

2023-01-22 12:01 UTC, dollorofkorea approved these changes, later dismissed
고생많으셨습니다!

2023-01-22 12:03 UTC, Jeremy-Kr requested changes
엄... 지금 보니 파일명이 ButtonComponents로 되어있는데 CustomButton이 더 적절 해 보입니다! 변경해서 커밋 부탁드려요

2023-01-22 12:30 UTC, frankkim92 commented on src/components/common/ButtonComponents.tsx
> +      ? (props: any) => props.theme.colors[`${props.backgroundColor}`]
정익님, 말씀해주신대로 파일명 CustomButton으로 수정을 완료했습니다.
또한 CustomInput 기능도 커밋 완료하였습니다.

2023-01-22 12:32 UTC, frankkim92 commented
> 엄... 지금 보니 파일명이 ButtonComponents로 되어있는데 CustomButton이 더 적절 해 보입니다! 변경해서 커밋 부탁드려요

변경 완료하였습니다.

2023-01-23 03:51 UTC, Jeremy-Kr approved these changes, later dismissed
LGTM 커스텀 인풋도 같이 들어가있네요! 다른 팀원분들도 확인 해 주시고, 혹시 placeholder는 따로 지정 안해줘도 될까요? 확인 부탁드려요! @frankkim92

2023-01-23 03:57 UTC, harenohee approved these changes, later dismissed
커스텀인풋 확인했습니다. 🥹

2023-01-25 01:56 UTC, ambition0103 commented
고생하셨습니다 .. 굿

2023-01-25 01:58 UTC, Jeremy-Kr approved these changes
LGTM

2023-01-25 02:10 UTC, ambition0103 approved these changes
고생하셨습니다.

2023-01-25 02:42 UTC, merged