feat : auth-logic 진행합니다.( 일부 UI는 진행 전인 상태로 코드 리뷰를 먼저 후 진행하고자 해서 진행합니다.)
money-fragments/money-fragments-client pull request #36
Opened 2023-01-25 06:51 UTC by dollorofkorea

## What is this PR? :mag:

- Auth를 사용할 수 있습니다. 로그인 한 사람만 main 화면으로 들어갈 수 있습니다.

## branch

- feat/Auth-logic -> develop

## Changes :memo:

- login와 SignUp모두 가능하며, 소셜 로그인(깃헙과 구글 )가능합니다.
- 비밀번호를 잃어버렸을 때 이제 찾을 수 있습니다.
- main화면에 임시 로그아웃 버튼을 생성하여 test하였으며, 로그아웃 시 landing으로 진행합니다.
- AuthRoute에서 로그인 여부를 통제합니다. 
- Router에 비로그인 시 통제 대상을 지정하여 진행합니다.
- UI작업 시 사용하지 않는 Import와 코드 정리할 예정입니다.

#5 #9 
by @dollorofkorea

2023-01-25 08:47 UTC, Jeremy-Kr commented
확인중입니다~ 리뷰 끝나고 한번에 코멘트 드릴게요!

2023-01-25 10:45 UTC, Jeremy-Kr requested changes
리뷰 확인해주세요!

2023-01-25 10:45 UTC, Jeremy-Kr commented on src/components/auth/AuthLogout.tsx
> +const AuthLogout = (): JSX.Element => {
요 컴포넌트는 무슨역할일까요? 로그아웃은 버튼으로만 처리해도 되지 않을까요?

2023-01-25 10:45 UTC, Jeremy-Kr commented on src/components/auth/AuthSocial.tsx
> +        console.log(response.user.uid);
콘솔 지우고 다시 커밋해주세요!

2023-01-25 10:45 UTC, Jeremy-Kr commented on src/components/auth/AuthSocial.tsx
> +        console.log(error);
콘솔 지우고 다시 커밋해주세요! 2

2023-01-25 10:45 UTC, Jeremy-Kr commented on src/components/auth/AuthSocial.tsx
> +        console.log(response.user.uid);
콘솔 지우고 다시 커밋해주세요! 3

2023-01-25 10:45 UTC, Jeremy-Kr commented on src/components/auth/AuthSocial.tsx
> +        console.log(error);
콘솔 지우고 다시 커밋해주세요! 4

2023-01-25 10:45 UTC, Jeremy-Kr commented on src/components/auth/Login.tsx
> +      </PwForgotContainer>
저희 디자인대로 다시 한글로 바꿔주세요!

2023-01-25 10:45 UTC, Jeremy-Kr commented on src/components/auth/SignUp.tsx
> +          <SignUpCheckSign>Already have an account?</SignUpCheckSign>
요기도 한글로 바꿔주세요

2023-01-25 10:45 UTC, Jeremy-Kr commented on src/components/auth/logging.tsx
> +export default logging;
저희 에러 로깅 하고있지 않으니까 필요 없는 파일 같습니다!

2023-01-25 10:45 UTC, Jeremy-Kr commented on src/shared/AuthRoute.tsx
> +export default AuthRoute;
굳이 이렇게 처리하신 이유가 있으실까요?

2023-01-25 10:45 UTC, Jeremy-Kr commented on src/shared/Router.tsx
> +        />
굳이 이렇게 처리하신 이유가 있으실까요?2

2023-01-25 10:56 UTC, frankkim92 approved these changes, later dismissed
LGTM

2023-01-25 11:05 UTC, ambition0103 submitted a review, later dismissed
LGTM

2023-01-25 11:52 UTC, dollorofkorea commented on src/shared/AuthRoute.tsx
> +export default AuthRoute;
목적은 제한을 걸고자 진행하였습니다. 하나의 component로 따로 분리해서 진행하여 로그인 아닌 상태를 관리하고자 한 의도였습니다.

2023-01-25 11:53 UTC, dollorofkorea commented on src/shared/Router.tsx
> +        />
필요한 구간만 로그인 없이 진행 시 로그인 유도로 진행하고자 한 의도였습니다.

2023-01-25 11:53 UTC, dollorofkorea commented on src/components/auth/logging.tsx
> +export default logging;
네. 일단 로깅을 하는 것이 좋다고 해서 그렇게 찾아 판단되어 작업하였습니다. 삭제하겠습니다.

2023-01-25 11:54 UTC, dollorofkorea commented on src/components/auth/SignUp.tsx
> +          <SignUpCheckSign>Already have an account?</SignUpCheckSign>
네 한글로 변경하겠습니다.

2023-01-25 11:54 UTC, dollorofkorea commented on src/components/auth/Login.tsx
> +      </PwForgotContainer>
네 한글로 변경하겠습니다.'

2023-01-25 11:54 UTC, dollorofkorea commented on src/components/auth/AuthSocial.tsx
> +        console.log(error);
콘솔 테스트한 부분 모두 삭제하겠습니다.

2023-01-25 11:54 UTC, dollorofkorea commented on src/components/auth/AuthSocial.tsx
> +        console.log(response.user.uid);
콘솔 테스트한 부분 모두 삭제하겠습니다.

2023-01-25 11:54 UTC, dollorofkorea commented on src/components/auth/AuthSocial.tsx
> +        console.log(error);
콘솔 테스트한 부분 모두 삭제하겠습니다.

2023-01-25 11:54 UTC, dollorofkorea commented on src/components/auth/AuthSocial.tsx
> +        console.log(response.user.uid);
콘솔 테스트한 부분 모두 삭제하겠습니다.

2023-01-25 11:55 UTC, dollorofkorea commented on src/components/auth/AuthLogout.tsx
> +const AuthLogout = (): JSX.Element => {
로그아웃 시 한번 더 확인하고 진행하고자 한 의도였습니다. 로그아웃 버튼을 실수로 누를 시 있다고 판단해서 component로 만들어 재차 확인하는 공간을 만들고자 했습니다.

2023-01-25 11:56 UTC, Jeremy-Kr commented on src/components/auth/AuthLogout.tsx
> +const AuthLogout = (): JSX.Element => {
> 로그아웃 시 한번 더 확인하고 진행하고자 한 의도였습니다. 로그아웃 버튼을 실수로 누를 시 있다고 판단해서 component로 만들어 재차 확인하는 공간을 만들고자 했습니다.

그러면 컴포넌트로 보내는 것 보다, confirm으로 처리하는게 더 좋을 것 같습니다!

2023-01-25 12:20 UTC, Jeremy-Kr commented on src/shared/Router.tsx
> +        />
좋은 방법인것 같습니다! 요 리뷰는 리졸브 할게요~!

2023-01-26 00:04 UTC, Jeremy-Kr submitted a review, later dismissed

2023-01-26 00:26 UTC, merged